name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and push the Docker image
      run: |
        docker buildx create --use
        REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        IMAGE_TAG=ghcr.io/$REPO_OWNER/$REPO_NAME:$(date +%Y%m%d%H%M%S)
        docker buildx build --platform linux/amd64,linux/arm64/v8 --file Dockerfile --tag $IMAGE_TAG --push .

    - name: Log out from GitHub Container Registry
      run: docker logout ghcr.io
